version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo
    container_name: audiobooks_mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-123456}
    volumes:
      - mongodb-data:/data/db
      - ./docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - audiobooks-network
    restart: unless-stopped

  # MongoDB Admin Interface
  mongo-express:
    image: mongo-express
    container_name: audiobooks_mongo_express
    ports:
      - "${MONGO_EXPRESS_PORT:-28081}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-123456}
      ME_CONFIG_MONGODB_SERVER: audiobooks_mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-user}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongodb
    networks:
      - audiobooks-network
    restart: unless-stopped

  # Node.js Backend
  backend:
    image: node:16-alpine
    container_name: audiobooks_backend
    working_dir: /app
    ports:
      - "${BACKEND_PORT:-23000}:3000"
    volumes:
      - ./BackEnd:/app
    environment:
      - PORT=3000
      - HOST_NAME=${HOST_NAME:-localhost}
      - MONGO_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-123456}@audiobooks_mongodb:27017/${MONGO_DATABASE:-audiobooksDB}?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-30d}
      - EMAIL_NAME=${EMAIL_NAME:-your_email@gmail.com}
      - EMAIL_PASS=${EMAIL_PASS:-your_email_app_password}
      - OTP_SECRET=${OTP_SECRET:-your_otp_secret_key_here}
    depends_on:
      - mongodb
    networks:
      - audiobooks-network
    restart: unless-stopped
    command: sh -c "npm install && npm start"

  # FastAPI TTS Service with VietTTS
  tts-service:
    build:
      context: ./tts-service
      dockerfile: Dockerfile
    container_name: audiobooks_tts
    working_dir: /app
    ports:
      - "${TTS_PORT:-28000}:8000"
    volumes:
      - ./tts-service:/app
      - ./logs:/app/logs
      - ./temp/tts_temp:/tmp/tts_temp
      - ./temp/tts_uploads:/tmp/tts_uploads
      - viettts_models:/root/.config/vietTTS
      - ./.env:/app/.env
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-123456}@audiobooks_mongodb:27017/${MONGO_DATABASE:-audiobooksDB}?authSource=admin
      - MONGODB_DATABASE=${MONGO_DATABASE:-audiobooksDB}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=${DEBUG:-True}
      - PROJECT_NAME=${PROJECT_NAME:-TTS Service}
      - SECRET_KEY=${TTS_SECRET_KEY:-your_secret_key_here}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-your-firebase-project-id}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY:-your-firebase-private-key}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL:-your-firebase-client-email}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET:-your-firebase-storage-bucket}
      - DEFAULT_VOICE_MODEL=${DEFAULT_VOICE_MODEL:-female}
      - CHUNK_SIZE=${CHUNK_SIZE:-5000}
      - TTS_TEMP_DIR=/tmp/tts_temp
      - PYTHONPATH=/app:/opt/vietTTS
    depends_on:
      - mongodb
    networks:
      - audiobooks-network
    restart: unless-stopped

networks:
  audiobooks-network:
    driver: bridge

volumes:
  mongodb-data:
  viettts_models: